apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    env: prod
spec:
  containers:
    - name: nginx-pod
      imagePullPolicy: Always
      image: clm-pun-tl5sm0.bmc.com:5000/nginx/nginx
    